### ISSUE TITLE
dependencies script not running

### ISSUE THREAD

**Issue by soni17** [phpenv/phpenv-installer#10]
php-build has a script called `install-dependencies.sh`  and it does not run during the execution of phpenv-installer
Without those dependencies, I've always gotten error when trying to install any php version.  

My recommendation is to run it in `phpenv-installer`

**Comment by giammyisjammy** [comment]
Kinda the same problem here. I've installed `phpenv` using the recommended [phpenv-installer](https://github.com/phpenv/phpenv-installer) but noticed that my `$PATH` didn't get updated and I had to manually update my `.zshrc`/`.bashrc` as per the [instructions for manual install](https://github.com/phpenv/phpenv?tab=readme-ov-file#basic-github-checkout). It seems to me that if installing with `phpenv-installer` I don't have to do those manual steps but correct me if I'm wrong.

Then I've tried running `phpenv install 8.1.11` without success and stumbled upon many errors from missing/mismatching packages like `libxml-2.0` and `openssl`. I've manually launched `~/.phpenv/plugins/php-build/install-dependencies.sh` and retried `phpenv install 8.1.11` this time with success.

Could it be because I'm running the commands from a non-`bash` shell? I admit I'm a noobie to the whole `php`/`phpenv` ecosystem, could easily be that I'm overlooking something.

For reference, these are some specs of the system I'm trying to install: 
```shell
OS: Kubuntu 22.04.4 LTS x86_64 
Kernel: 6.5.0-28-generic
Shell: zsh 5.8.1 
Terminal: konsole 
```

**Comment by soni17** [comment]
I had the same experience. Had to run `~/.phpenv/plugins/php-build/install-dependencies.sh` or else php would not install. php-build requires a few dependencies. Without those dependenices, php cannot be installed. 

In my opinion, `~/.phpenv/plugins/php-build/install-dependencies.sh` should always run during the installation of `phpenv`
