### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by allanlaal** [phpenv/phpenv-installer#7]
allan@L4:~$ curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer \
	      | bash
	    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                   Dload  Upload   Total   Spent    Left  Speed
	  100  3685  100  3685    0     0  15040      0 --:--:-- --:--:-- --:--:-- 15102
	  INFO
	   |  $PHPENV_ROOT is defined as /home/allan/.phpenv
	  
	  Installing phpenv
	  fatal: not a git repository (or any of the parent directories): .git
	  allan@L4:~$

**Comment by debo** [comment]
Hi @allanlaal is it the first time you try to install phpenv? Does your `~/.phpenv` folder already exist? If it's already there from a previous installation or similar I would suggest trying removing the folder and try again.

Because by the look of it it seems that in your case the installer is executing [this line](https://github.com/phpenv/phpenv-installer/blob/master/bin/phpenv-installer#L61) which is not a clone but a pull and if there is no git repository initialise in such destination as you know it will fail.

Or it could also be that you are executing [this other line](https://github.com/phpenv/phpenv-installer/blob/master/bin/phpenv-installer#L34) which, again, has a similar issue. I hope that helps.

**Comment by allanlaal** [comment]
yes, indeed I already had installed php-env from another source
I deleted my old phpenv & php-build and then ran this installer again
success!

**Comment by debo** [comment]
I'm glad it helped and you resolved the issue.
